languageCode = "hr"
languageName = "Croatian"
displayName = "Hr"
isoCode = "hr"
weight = 3
rtl = false

title = "Luka Piplica"
# logo = "img/logo.png"
description = "Bok, ja sam Luka i ovo je moja web stranica. Zainteresovan sam za sve što je povezano s tehnologijom. Ova web stranica je mjesto na kojem mogu podijeliti svoje znanje i projekte te može poslužiti u svrhu dokumentacije. Hvala na posjeti."
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Luka Piplica"
  image = "img/logo.webp"
  headline = "Kibernetička sigurnost, elektronika, administracija sustava i mreže"
  bio = "Bok, ja sam Luka i ovo je moja web stranica. Zainteresovan sam za sve što je povezano s tehnologijom. Ova web stranica je mjesto na kojem mogu podijeliti svoje znanje i projekte te može poslužiti u svrhu dokumentacije. Hvala na posjeti."
    links = [
      { email = "mailto:lukapiplica@protonmail.ch" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
      { github = "https://github.com/lukapiplica" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
      { linkedin = "https://linkedin.com/in/lukapiplica" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
    ]
